  steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}", "."]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    secretEnv: ['DATABASE_PASS']
    env:
      - 'DATABASE_PORT=6543'
      - 'DATABASE_HOST=db.xhnfyalwyezgaisbumtw.supabase.co'
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]

  - id: "collect static"
    name: "gcr.io/google-appengine/exec-wrapper"
    secretEnv: ['DATABASE_PASS']
    env:
      - 'DATABASE_PORT=6543'
      - 'DATABASE_HOST=db.xhnfyalwyezgaisbumtw.supabase.co'
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "--",
        "python",
        "manage.py",
        "collectstatic",
        "--verbosity",
        "2",
        "--no-input",
      ]

substitutions:
  _REGION: us-west1
  _SERVICE_NAME: django2
  _SECRET_SETTINGS_NAME: djangosecret

availableSecrets:
  secretManager:
  - versionName: projects/django-341122/secrets/djangopass/versions/1
    env: DATABASE_PASS

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"